cache:
  cache_to_prod: False
  cache_from_prod: False
  root_prod_relative_to_data_root: "04_outputs/0_data_archive"
  root_local_relative_to_home: "Documents/04_PERSO/Immo/immo_cache"
  write_kwargs:
    csv:
      sep: "|"
      decimal: "."
      encoding: utf-8
      header: True
      index: False
  read_kwargs:
    csv:
      sep: "|"
      decimal: "."
      encoding: utf-8
      dtype:
        UPC: str
        sku_id: str
      parse_dates:
        - promo_start_date
        - start_promo_week
        - promo_end_date
        - end_promo_week
        - date
        - predict_dt
        - info_dt

raw_data:
  agency_master:
    location: 02_agency_fees/agency_master
    filename: adresses_all_distinct.csv
    format: csv
    read_kwargs:
      sep: ","
      usecols: ["adresse","Code Postal","Ville","agence_name", "tel_1","agence_url","image_url","nb_avis","note","Prestations","Reseaux","teaser-avis","agences_urls"]

  filled_agency_fees:
    location: 02_agency_fees/filled/75002
    filename: 20201011_list_agencies_filled_tb_75002.xlsx
    format: xlsx
    read_kwargs:
      usecols: ["comment","is_non-standard","is_agency","tarif_dispo-web","agency_code","agency_name","agency_address","postal_code","city","price_min","agency_rate","agency_fee_min_keuros"]

no_update_etls: []

manual_overlay:
  use: False
  location: 03_external/05_manual_updates
  read_kwargs:
    sep: "|"
    decimal: "."
    encoding: utf-8
    dtype:
      sku_id: str
