cache:
  cache_to_prod: False
  cache_from_prod: False
  root_prod_relative_to_data_root: "04_outputs/0_data_archive"
  root_local_relative_to_home: "Documents/04_PERSO/Immo/immo_cache"
  write_kwargs:
    csv:
      sep: "|"
      decimal: "."
      encoding: utf-8
      header: True
      index: False
  read_kwargs:
    csv:
      sep: "|"
      decimal: "."
      encoding: utf-8
      dtype:
        UPC: str
        sku_id: str
      parse_dates:
        - promo_start_date
        - start_promo_week
        - promo_end_date
        - end_promo_week
        - date
        - predict_dt
        - info_dt

raw_data:
  agency_master:
    location: 02_agency_fees/agency_master
    filename: all_info_pj_url.csv
    format: csv
    read_kwargs:
      sep: ","
      usecols: ["adresse","Code Postal","Ville","agence_name", "tel_1","agence_url_0","image_url","nb_avis","note","prestations","reseaux","teaser-avis","url_pj","agence_id"]

  filled_agency_fees:
    location: 02_agency_fees/filled/
    filename: 20210117_list_agencies_filled_01_02_05_06_07_08_09_12_13_14_15_16_17.xlsx
    format: xlsx
    read_kwargs:
      usecols: ["Comment","is_non-standard","Is_agency","tarif_dispo-web","agency_name","agency_address","postal_code","city","price_min","agency_rate","agency_fee_min_keuros","agency_url"]

no_update_etls: []

manual_overlay:
  use: False
  location: 03_external/05_manual_updates
  read_kwargs:
    sep: "|"
    decimal: "."
    encoding: utf-8
    dtype:
      sku_id: str
