name: immoproject
channels:
  - conda-forge
  - Gurobi
dependencies:
  - python=3.7
  - black=19.10
  - flake8=3.7.9
  - pandas=1.0.1
  - numpy=1.18.1
  - pyspark=2.4.4
  - pytest=5.3.5
  - pre_commit=1.18.1
  - scipy=1.4.1
  - gurobi=8.1.1
  - matplotlib=3.0.1
  - pyyaml==3.13
  - pytest-cov==2.6.0
  - pyodbc==4.0.24
  - cached-property==1.5.1
  - pathlib2==2.3.2
  - pathlib==1.0.1
  - sqlalchemy==1.2.14
  - psycopg2==2.7.5
  - msrestazure==0.6.0
  - pymemcache==2.0.0
  - pylint==2.2.2
  - bokeh==1.0.2
  - scikit-learn==0.20.3
  - beautifulsoup4==4.7.1
  - openpyxl==2.6.1
  - python-snappy==0.5.4
  - pyarrow=0.13.0
  - dill=0.3.1.1
  - lightgbm=2.3.1
  - ipython
  - pip
  - plotly
  - jupyter
  - xgboost==1.0.2
  - nbsphinx==0.7
  - sphinx==3.1.2
  - sphinxcontrib-napoleon==0.7
  - pip:
    - xlrd==1.2.0
    - statsmodels
    - presto-python-client
    - colorlog
    - azure-datalake-store==0.0.39
    - azure-keyvault==1.1.0
    - applicationinsights==0.11.7
    - redis==3.2.1
    - docker==3.7.1
    - knapsack==0.0.4
    - statsd==3.3.0
    - prometheus_client==0.6.0
    - sphinx-rtd-theme==0.5.0
    - recommonmark==0.6.0
    - m2r==0.2.1
    - sphinx-math-dollar
